run:
  timeout: 2m

linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 150
    statements: 70
  gci:
    local-prefixes: github.com/dominodatalab/distributed-compute-operator
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 25
  goimports:
    local-prefixes: github.com/dominodatalab/distributed-compute-operator
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
        ignored-functions: log.V
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nestif:
    min-complexity: 6

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - exhaustive
        - gocyclo
        - gomnd
        - gosec
        - funlen
    - path: test/test.go
      linters:
        - dogsled
    - source: "^//\\s*\\+kubebuilder:.+"
      linters:
        - lll
  exclude:
    - Using the variable on range scope `tc` in function literal

