before:
  hooks:
    - scripts/release/before-hook.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - custom-resource-definitions/*.yaml
      - deploy/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
