/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dominodatalab.distributedcomputeoperator.spark.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1SparkClusterSpecAutoscaling
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-04T16:38:59.380Z[Etc/UTC]")
public class V1alpha1SparkClusterSpecAutoscaling {
  public static final String SERIALIZED_NAME_AVERAGE_C_P_U_UTILIZATION = "averageCPUUtilization";
  @SerializedName(SERIALIZED_NAME_AVERAGE_C_P_U_UTILIZATION)
  private Integer averageCPUUtilization;

  public static final String SERIALIZED_NAME_AVERAGE_MEMORY_UTILIZATION = "averageMemoryUtilization";
  @SerializedName(SERIALIZED_NAME_AVERAGE_MEMORY_UTILIZATION)
  private Integer averageMemoryUtilization;

  public static final String SERIALIZED_NAME_MAX_REPLICAS = "maxReplicas";
  @SerializedName(SERIALIZED_NAME_MAX_REPLICAS)
  private Integer maxReplicas;

  public static final String SERIALIZED_NAME_MIN_REPLICAS = "minReplicas";
  @SerializedName(SERIALIZED_NAME_MIN_REPLICAS)
  private Integer minReplicas;

  public static final String SERIALIZED_NAME_SCALE_DOWN_STABILIZATION_WINDOW_SECONDS = "scaleDownStabilizationWindowSeconds";
  @SerializedName(SERIALIZED_NAME_SCALE_DOWN_STABILIZATION_WINDOW_SECONDS)
  private Integer scaleDownStabilizationWindowSeconds;


  public V1alpha1SparkClusterSpecAutoscaling averageCPUUtilization(Integer averageCPUUtilization) {
    
    this.averageCPUUtilization = averageCPUUtilization;
    return this;
  }

   /**
   * Get averageCPUUtilization
   * @return averageCPUUtilization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAverageCPUUtilization() {
    return averageCPUUtilization;
  }


  public void setAverageCPUUtilization(Integer averageCPUUtilization) {
    this.averageCPUUtilization = averageCPUUtilization;
  }


  public V1alpha1SparkClusterSpecAutoscaling averageMemoryUtilization(Integer averageMemoryUtilization) {
    
    this.averageMemoryUtilization = averageMemoryUtilization;
    return this;
  }

   /**
   * Get averageMemoryUtilization
   * @return averageMemoryUtilization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAverageMemoryUtilization() {
    return averageMemoryUtilization;
  }


  public void setAverageMemoryUtilization(Integer averageMemoryUtilization) {
    this.averageMemoryUtilization = averageMemoryUtilization;
  }


  public V1alpha1SparkClusterSpecAutoscaling maxReplicas(Integer maxReplicas) {
    
    this.maxReplicas = maxReplicas;
    return this;
  }

   /**
   * Get maxReplicas
   * @return maxReplicas
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getMaxReplicas() {
    return maxReplicas;
  }


  public void setMaxReplicas(Integer maxReplicas) {
    this.maxReplicas = maxReplicas;
  }


  public V1alpha1SparkClusterSpecAutoscaling minReplicas(Integer minReplicas) {
    
    this.minReplicas = minReplicas;
    return this;
  }

   /**
   * Get minReplicas
   * @return minReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMinReplicas() {
    return minReplicas;
  }


  public void setMinReplicas(Integer minReplicas) {
    this.minReplicas = minReplicas;
  }


  public V1alpha1SparkClusterSpecAutoscaling scaleDownStabilizationWindowSeconds(Integer scaleDownStabilizationWindowSeconds) {
    
    this.scaleDownStabilizationWindowSeconds = scaleDownStabilizationWindowSeconds;
    return this;
  }

   /**
   * Get scaleDownStabilizationWindowSeconds
   * @return scaleDownStabilizationWindowSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getScaleDownStabilizationWindowSeconds() {
    return scaleDownStabilizationWindowSeconds;
  }


  public void setScaleDownStabilizationWindowSeconds(Integer scaleDownStabilizationWindowSeconds) {
    this.scaleDownStabilizationWindowSeconds = scaleDownStabilizationWindowSeconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SparkClusterSpecAutoscaling v1alpha1SparkClusterSpecAutoscaling = (V1alpha1SparkClusterSpecAutoscaling) o;
    return Objects.equals(this.averageCPUUtilization, v1alpha1SparkClusterSpecAutoscaling.averageCPUUtilization) &&
        Objects.equals(this.averageMemoryUtilization, v1alpha1SparkClusterSpecAutoscaling.averageMemoryUtilization) &&
        Objects.equals(this.maxReplicas, v1alpha1SparkClusterSpecAutoscaling.maxReplicas) &&
        Objects.equals(this.minReplicas, v1alpha1SparkClusterSpecAutoscaling.minReplicas) &&
        Objects.equals(this.scaleDownStabilizationWindowSeconds, v1alpha1SparkClusterSpecAutoscaling.scaleDownStabilizationWindowSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageCPUUtilization, averageMemoryUtilization, maxReplicas, minReplicas, scaleDownStabilizationWindowSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SparkClusterSpecAutoscaling {\n");
    sb.append("    averageCPUUtilization: ").append(toIndentedString(averageCPUUtilization)).append("\n");
    sb.append("    averageMemoryUtilization: ").append(toIndentedString(averageMemoryUtilization)).append("\n");
    sb.append("    maxReplicas: ").append(toIndentedString(maxReplicas)).append("\n");
    sb.append("    minReplicas: ").append(toIndentedString(minReplicas)).append("\n");
    sb.append("    scaleDownStabilizationWindowSeconds: ").append(toIndentedString(scaleDownStabilizationWindowSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

