/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dominodatalab.distributedcomputeoperator.spark.models;

import java.util.Objects;
import java.util.Arrays;
import com.dominodatalab.distributedcomputeoperator.spark.models.V1alpha1SparkClusterSpecMasterAffinity;
import com.dominodatalab.distributedcomputeoperator.spark.models.V1alpha1SparkClusterSpecMasterInitContainers;
import com.dominodatalab.distributedcomputeoperator.spark.models.V1alpha1SparkClusterSpecMasterResources;
import com.dominodatalab.distributedcomputeoperator.spark.models.V1alpha1SparkClusterSpecMasterTolerations;
import com.dominodatalab.distributedcomputeoperator.spark.models.V1alpha1SparkClusterSpecMasterVolumeClaimTemplates;
import com.dominodatalab.distributedcomputeoperator.spark.models.V1alpha1SparkClusterSpecMasterVolumeMounts;
import com.dominodatalab.distributedcomputeoperator.spark.models.V1alpha1SparkClusterSpecMasterVolumes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1SparkClusterSpecWorker
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-04T16:38:59.380Z[Etc/UTC]")
public class V1alpha1SparkClusterSpecWorker {
  public static final String SERIALIZED_NAME_AFFINITY = "affinity";
  @SerializedName(SERIALIZED_NAME_AFFINITY)
  private V1alpha1SparkClusterSpecMasterAffinity affinity;

  public static final String SERIALIZED_NAME_ANNOTATIONS = "annotations";
  @SerializedName(SERIALIZED_NAME_ANNOTATIONS)
  private Map<String, String> annotations = null;

  public static final String SERIALIZED_NAME_DEFAULT_CONFIGURATION = "defaultConfiguration";
  @SerializedName(SERIALIZED_NAME_DEFAULT_CONFIGURATION)
  private Map<String, String> defaultConfiguration = null;

  public static final String SERIALIZED_NAME_INIT_CONTAINERS = "initContainers";
  @SerializedName(SERIALIZED_NAME_INIT_CONTAINERS)
  private List<V1alpha1SparkClusterSpecMasterInitContainers> initContainers = null;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private Map<String, String> labels = null;

  public static final String SERIALIZED_NAME_NODE_SELECTOR = "nodeSelector";
  @SerializedName(SERIALIZED_NAME_NODE_SELECTOR)
  private Map<String, String> nodeSelector = null;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private V1alpha1SparkClusterSpecMasterResources resources;

  public static final String SERIALIZED_NAME_TOLERATIONS = "tolerations";
  @SerializedName(SERIALIZED_NAME_TOLERATIONS)
  private List<V1alpha1SparkClusterSpecMasterTolerations> tolerations = null;

  public static final String SERIALIZED_NAME_VOLUME_CLAIM_TEMPLATES = "volumeClaimTemplates";
  @SerializedName(SERIALIZED_NAME_VOLUME_CLAIM_TEMPLATES)
  private List<V1alpha1SparkClusterSpecMasterVolumeClaimTemplates> volumeClaimTemplates = null;

  public static final String SERIALIZED_NAME_VOLUME_MOUNTS = "volumeMounts";
  @SerializedName(SERIALIZED_NAME_VOLUME_MOUNTS)
  private List<V1alpha1SparkClusterSpecMasterVolumeMounts> volumeMounts = null;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  private List<V1alpha1SparkClusterSpecMasterVolumes> volumes = null;


  public V1alpha1SparkClusterSpecWorker affinity(V1alpha1SparkClusterSpecMasterAffinity affinity) {
    
    this.affinity = affinity;
    return this;
  }

   /**
   * Get affinity
   * @return affinity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1SparkClusterSpecMasterAffinity getAffinity() {
    return affinity;
  }


  public void setAffinity(V1alpha1SparkClusterSpecMasterAffinity affinity) {
    this.affinity = affinity;
  }


  public V1alpha1SparkClusterSpecWorker annotations(Map<String, String> annotations) {
    
    this.annotations = annotations;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker putAnnotationsItem(String key, String annotationsItem) {
    if (this.annotations == null) {
      this.annotations = new HashMap<>();
    }
    this.annotations.put(key, annotationsItem);
    return this;
  }

   /**
   * Get annotations
   * @return annotations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getAnnotations() {
    return annotations;
  }


  public void setAnnotations(Map<String, String> annotations) {
    this.annotations = annotations;
  }


  public V1alpha1SparkClusterSpecWorker defaultConfiguration(Map<String, String> defaultConfiguration) {
    
    this.defaultConfiguration = defaultConfiguration;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker putDefaultConfigurationItem(String key, String defaultConfigurationItem) {
    if (this.defaultConfiguration == null) {
      this.defaultConfiguration = new HashMap<>();
    }
    this.defaultConfiguration.put(key, defaultConfigurationItem);
    return this;
  }

   /**
   * Get defaultConfiguration
   * @return defaultConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getDefaultConfiguration() {
    return defaultConfiguration;
  }


  public void setDefaultConfiguration(Map<String, String> defaultConfiguration) {
    this.defaultConfiguration = defaultConfiguration;
  }


  public V1alpha1SparkClusterSpecWorker initContainers(List<V1alpha1SparkClusterSpecMasterInitContainers> initContainers) {
    
    this.initContainers = initContainers;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker addInitContainersItem(V1alpha1SparkClusterSpecMasterInitContainers initContainersItem) {
    if (this.initContainers == null) {
      this.initContainers = new ArrayList<>();
    }
    this.initContainers.add(initContainersItem);
    return this;
  }

   /**
   * Get initContainers
   * @return initContainers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SparkClusterSpecMasterInitContainers> getInitContainers() {
    return initContainers;
  }


  public void setInitContainers(List<V1alpha1SparkClusterSpecMasterInitContainers> initContainers) {
    this.initContainers = initContainers;
  }


  public V1alpha1SparkClusterSpecWorker labels(Map<String, String> labels) {
    
    this.labels = labels;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker putLabelsItem(String key, String labelsItem) {
    if (this.labels == null) {
      this.labels = new HashMap<>();
    }
    this.labels.put(key, labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getLabels() {
    return labels;
  }


  public void setLabels(Map<String, String> labels) {
    this.labels = labels;
  }


  public V1alpha1SparkClusterSpecWorker nodeSelector(Map<String, String> nodeSelector) {
    
    this.nodeSelector = nodeSelector;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker putNodeSelectorItem(String key, String nodeSelectorItem) {
    if (this.nodeSelector == null) {
      this.nodeSelector = new HashMap<>();
    }
    this.nodeSelector.put(key, nodeSelectorItem);
    return this;
  }

   /**
   * Get nodeSelector
   * @return nodeSelector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getNodeSelector() {
    return nodeSelector;
  }


  public void setNodeSelector(Map<String, String> nodeSelector) {
    this.nodeSelector = nodeSelector;
  }


  public V1alpha1SparkClusterSpecWorker replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Get replicas
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1alpha1SparkClusterSpecWorker resources(V1alpha1SparkClusterSpecMasterResources resources) {
    
    this.resources = resources;
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1SparkClusterSpecMasterResources getResources() {
    return resources;
  }


  public void setResources(V1alpha1SparkClusterSpecMasterResources resources) {
    this.resources = resources;
  }


  public V1alpha1SparkClusterSpecWorker tolerations(List<V1alpha1SparkClusterSpecMasterTolerations> tolerations) {
    
    this.tolerations = tolerations;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker addTolerationsItem(V1alpha1SparkClusterSpecMasterTolerations tolerationsItem) {
    if (this.tolerations == null) {
      this.tolerations = new ArrayList<>();
    }
    this.tolerations.add(tolerationsItem);
    return this;
  }

   /**
   * Get tolerations
   * @return tolerations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SparkClusterSpecMasterTolerations> getTolerations() {
    return tolerations;
  }


  public void setTolerations(List<V1alpha1SparkClusterSpecMasterTolerations> tolerations) {
    this.tolerations = tolerations;
  }


  public V1alpha1SparkClusterSpecWorker volumeClaimTemplates(List<V1alpha1SparkClusterSpecMasterVolumeClaimTemplates> volumeClaimTemplates) {
    
    this.volumeClaimTemplates = volumeClaimTemplates;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker addVolumeClaimTemplatesItem(V1alpha1SparkClusterSpecMasterVolumeClaimTemplates volumeClaimTemplatesItem) {
    if (this.volumeClaimTemplates == null) {
      this.volumeClaimTemplates = new ArrayList<>();
    }
    this.volumeClaimTemplates.add(volumeClaimTemplatesItem);
    return this;
  }

   /**
   * Get volumeClaimTemplates
   * @return volumeClaimTemplates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SparkClusterSpecMasterVolumeClaimTemplates> getVolumeClaimTemplates() {
    return volumeClaimTemplates;
  }


  public void setVolumeClaimTemplates(List<V1alpha1SparkClusterSpecMasterVolumeClaimTemplates> volumeClaimTemplates) {
    this.volumeClaimTemplates = volumeClaimTemplates;
  }


  public V1alpha1SparkClusterSpecWorker volumeMounts(List<V1alpha1SparkClusterSpecMasterVolumeMounts> volumeMounts) {
    
    this.volumeMounts = volumeMounts;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker addVolumeMountsItem(V1alpha1SparkClusterSpecMasterVolumeMounts volumeMountsItem) {
    if (this.volumeMounts == null) {
      this.volumeMounts = new ArrayList<>();
    }
    this.volumeMounts.add(volumeMountsItem);
    return this;
  }

   /**
   * Get volumeMounts
   * @return volumeMounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SparkClusterSpecMasterVolumeMounts> getVolumeMounts() {
    return volumeMounts;
  }


  public void setVolumeMounts(List<V1alpha1SparkClusterSpecMasterVolumeMounts> volumeMounts) {
    this.volumeMounts = volumeMounts;
  }


  public V1alpha1SparkClusterSpecWorker volumes(List<V1alpha1SparkClusterSpecMasterVolumes> volumes) {
    
    this.volumes = volumes;
    return this;
  }

  public V1alpha1SparkClusterSpecWorker addVolumesItem(V1alpha1SparkClusterSpecMasterVolumes volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

   /**
   * Get volumes
   * @return volumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SparkClusterSpecMasterVolumes> getVolumes() {
    return volumes;
  }


  public void setVolumes(List<V1alpha1SparkClusterSpecMasterVolumes> volumes) {
    this.volumes = volumes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SparkClusterSpecWorker v1alpha1SparkClusterSpecWorker = (V1alpha1SparkClusterSpecWorker) o;
    return Objects.equals(this.affinity, v1alpha1SparkClusterSpecWorker.affinity) &&
        Objects.equals(this.annotations, v1alpha1SparkClusterSpecWorker.annotations) &&
        Objects.equals(this.defaultConfiguration, v1alpha1SparkClusterSpecWorker.defaultConfiguration) &&
        Objects.equals(this.initContainers, v1alpha1SparkClusterSpecWorker.initContainers) &&
        Objects.equals(this.labels, v1alpha1SparkClusterSpecWorker.labels) &&
        Objects.equals(this.nodeSelector, v1alpha1SparkClusterSpecWorker.nodeSelector) &&
        Objects.equals(this.replicas, v1alpha1SparkClusterSpecWorker.replicas) &&
        Objects.equals(this.resources, v1alpha1SparkClusterSpecWorker.resources) &&
        Objects.equals(this.tolerations, v1alpha1SparkClusterSpecWorker.tolerations) &&
        Objects.equals(this.volumeClaimTemplates, v1alpha1SparkClusterSpecWorker.volumeClaimTemplates) &&
        Objects.equals(this.volumeMounts, v1alpha1SparkClusterSpecWorker.volumeMounts) &&
        Objects.equals(this.volumes, v1alpha1SparkClusterSpecWorker.volumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affinity, annotations, defaultConfiguration, initContainers, labels, nodeSelector, replicas, resources, tolerations, volumeClaimTemplates, volumeMounts, volumes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SparkClusterSpecWorker {\n");
    sb.append("    affinity: ").append(toIndentedString(affinity)).append("\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("    defaultConfiguration: ").append(toIndentedString(defaultConfiguration)).append("\n");
    sb.append("    initContainers: ").append(toIndentedString(initContainers)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    nodeSelector: ").append(toIndentedString(nodeSelector)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    tolerations: ").append(toIndentedString(tolerations)).append("\n");
    sb.append("    volumeClaimTemplates: ").append(toIndentedString(volumeClaimTemplates)).append("\n");
    sb.append("    volumeMounts: ").append(toIndentedString(volumeMounts)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

