# permissions for end users to view daskclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daskcluster-viewer-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - daskclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - daskclusters/status
  verbs:
  - get
