# permissions for end users to edit daskclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daskcluster-editor-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - daskclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - daskclusters/status
  verbs:
  - get
