# permissions for end users to view mpiclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpicluster-viewer-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - mpiclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - mpiclusters/status
  verbs:
  - get
