# permissions for end users to view mpijobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpijob-viewer-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - mpijobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - mpijobs/status
  verbs:
  - get
