# permissions for end users to edit mpijobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpijob-editor-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - mpijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - mpijobs/status
  verbs:
  - get
