# permissions for end users to view rayclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raycluster-viewer-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - rayclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - rayclusters/status
  verbs:
  - get
