# permissions for end users to edit rayclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raycluster-editor-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - rayclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - rayclusters/status
  verbs:
  - get
