
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - rayclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - rayclusters/finalizers
  verbs:
  - update
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - rayclusters/status
  verbs:
  - get
  - patch
  - update
