USER-SUPPLIED VALUES:
image:
  registry: quay.io
  repository: domino/distributed-compute-operator
  tag: v0.7.3
  pullPolicy: Always
imagePullSecrets:
- name: domino-quay-repos
installCRDs: true
global:
  istio:
    cni: true
    enabled: false
    httpIdleTimeout:
      timeout: 24h
    install: false
    rootConfigNamespace: istio-system
mpi:
  initImage:
    registry: quay.io
    repository: domino/distributed-compute-operator-mpi-init
    tag: v0.7.3
  syncImage:
    registry: quay.io
    repository: domino/distributed-compute-operator-mpi-sync
    tag: v0.7.3
networkPolicy:
  enabled: true
nodeSelector:
  dominodatalab.com/node-pool: default
podAnnotations: {}
podEnv: []
podLabels: {}
podSecurityPolicy:
  enabled: true
priorityClassName: domino-default
prometheus:
  enabled: true
  namespaceLabels:
    domino-platform: "true"
rbac:
  pspEnabled: true
replicaCount: 1
securityContextConstraints:
  enabled: false
