# Default values for distributed-compute-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  istio:
    # Enable support for environments with Istio installed
    enabled: false
    # Elevate pod execution permissions so that Istio's init container can modify
    # network settings when CNI plugin is NOT installed
    cniPluginInstalled: true

# Number of controller instances to run
replicaCount: 1

# If true, CRD resources will be installed/uninstalled as part of the Helm chart release.
# Uninstalling CRD resources will DELETE all related custom resources.
installCRDs: true

# Controller manager configuration
config:
  # Limit watch to a specific set of namespaces, default is all namespaces.
  watchNamespaces: []

  # Webhook server port
  webhookPort: 9443
  # Prometheus metrics port
  metricsPort: 8080
  # Health probe port
  healthProbePort: 8081
  # Leader election ensures that only one controller instance is active at a time
  enableLeaderElection: false

  # Logger enconding can be either 'json' or 'console'
  logEncoder: ""
  # Logger level can be either 'debug', 'info', 'error', or any integer value >= 0 which corresponds to custom debug levels of increasing verbosity
  logLevel: ""
  # Logger level at which stacktraces are printed can either 'info', 'error', or 'panic'
  logStacktraceLevel: panic
  # Development mode enables debug logging, console output and stacktraces suitable for troubleshooting
  logDevelopmentMode: false

podSecurityPolicy:
  # Create custom PSP for operator
  enabled: true

networkPolicy:
  # Restrict network ingress to operator pods
  enabled: false

prometheus:
  # Enable prometheus scraping
  enabled: true
  # Allow ingress traffic from prometheus pods with the following labels
  podLabels:
    app.kubernetes.io/name: prometheus
  # Namespace labels where prometheus is running if different from app's namespace
  namespaceLabels: {}

image:
  registry: quay.io
  repository: domino/distributed-compute-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: main

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podLabels: {}
podAnnotations: {}
podEnv: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  # fsGroup: 2000
  seLinuxOptions:
    type: spc_t

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""

nameOverride: ""
fullnameOverride: ""

mpi:
  # For both images:
  # - A pull policy is the same as for the main MPI Worker image.
  # - All three fields must be provided.
  initImage:
    registry: quay.io
    repository: domino/distributed-compute-operator-mpi-init
    tag: main
  syncImage:
    registry: quay.io
    repository: domino/distributed-compute-operator-mpi-sync
    tag: main

  clusterDomain: cluster.local
