/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dominodatalab.distributedcomputeoperator.dask.models;

import java.util.Objects;
import java.util.Arrays;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecAutoscaling;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecEnvVars;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecImage;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecImagePullSecrets;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecKerberosKeytab;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecNetworkPolicy;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecPodSecurityContext;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecScheduler;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecServiceAccount;
import com.dominodatalab.distributedcomputeoperator.dask.models.V1alpha1DaskClusterSpecWorker;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1DaskClusterSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-04T16:36:51.907Z[Etc/UTC]")
public class V1alpha1DaskClusterSpec {
  public static final String SERIALIZED_NAME_AUTOSCALING = "autoscaling";
  @SerializedName(SERIALIZED_NAME_AUTOSCALING)
  private V1alpha1DaskClusterSpecAutoscaling autoscaling;

  public static final String SERIALIZED_NAME_DASHBOARD_PORT = "dashboardPort";
  @SerializedName(SERIALIZED_NAME_DASHBOARD_PORT)
  private Integer dashboardPort;

  public static final String SERIALIZED_NAME_ENV_VARS = "envVars";
  @SerializedName(SERIALIZED_NAME_ENV_VARS)
  private List<V1alpha1DaskClusterSpecEnvVars> envVars = null;

  public static final String SERIALIZED_NAME_GLOBAL_LABELS = "globalLabels";
  @SerializedName(SERIALIZED_NAME_GLOBAL_LABELS)
  private Map<String, String> globalLabels = null;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private V1alpha1DaskClusterSpecImage image;

  public static final String SERIALIZED_NAME_IMAGE_PULL_SECRETS = "imagePullSecrets";
  @SerializedName(SERIALIZED_NAME_IMAGE_PULL_SECRETS)
  private List<V1alpha1DaskClusterSpecImagePullSecrets> imagePullSecrets = null;

  public static final String SERIALIZED_NAME_ISTIO_MUTUAL_T_L_S_MODE = "istioMutualTLSMode";
  @SerializedName(SERIALIZED_NAME_ISTIO_MUTUAL_T_L_S_MODE)
  private String istioMutualTLSMode;

  public static final String SERIALIZED_NAME_KERBEROS_KEYTAB = "kerberosKeytab";
  @SerializedName(SERIALIZED_NAME_KERBEROS_KEYTAB)
  private V1alpha1DaskClusterSpecKerberosKeytab kerberosKeytab;

  public static final String SERIALIZED_NAME_NANNY_PORT = "nannyPort";
  @SerializedName(SERIALIZED_NAME_NANNY_PORT)
  private Integer nannyPort;

  public static final String SERIALIZED_NAME_NETWORK_POLICY = "networkPolicy";
  @SerializedName(SERIALIZED_NAME_NETWORK_POLICY)
  private V1alpha1DaskClusterSpecNetworkPolicy networkPolicy;

  public static final String SERIALIZED_NAME_POD_SECURITY_CONTEXT = "podSecurityContext";
  @SerializedName(SERIALIZED_NAME_POD_SECURITY_CONTEXT)
  private V1alpha1DaskClusterSpecPodSecurityContext podSecurityContext;

  public static final String SERIALIZED_NAME_POD_SECURITY_POLICY = "podSecurityPolicy";
  @SerializedName(SERIALIZED_NAME_POD_SECURITY_POLICY)
  private String podSecurityPolicy;

  public static final String SERIALIZED_NAME_SCHEDULER = "scheduler";
  @SerializedName(SERIALIZED_NAME_SCHEDULER)
  private V1alpha1DaskClusterSpecScheduler scheduler;

  public static final String SERIALIZED_NAME_SCHEDULER_PORT = "schedulerPort";
  @SerializedName(SERIALIZED_NAME_SCHEDULER_PORT)
  private Integer schedulerPort;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT = "serviceAccount";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT)
  private V1alpha1DaskClusterSpecServiceAccount serviceAccount;

  public static final String SERIALIZED_NAME_WORKER = "worker";
  @SerializedName(SERIALIZED_NAME_WORKER)
  private V1alpha1DaskClusterSpecWorker worker;

  public static final String SERIALIZED_NAME_WORKER_PORT = "workerPort";
  @SerializedName(SERIALIZED_NAME_WORKER_PORT)
  private Integer workerPort;


  public V1alpha1DaskClusterSpec autoscaling(V1alpha1DaskClusterSpecAutoscaling autoscaling) {
    
    this.autoscaling = autoscaling;
    return this;
  }

   /**
   * Get autoscaling
   * @return autoscaling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecAutoscaling getAutoscaling() {
    return autoscaling;
  }


  public void setAutoscaling(V1alpha1DaskClusterSpecAutoscaling autoscaling) {
    this.autoscaling = autoscaling;
  }


  public V1alpha1DaskClusterSpec dashboardPort(Integer dashboardPort) {
    
    this.dashboardPort = dashboardPort;
    return this;
  }

   /**
   * Get dashboardPort
   * @return dashboardPort
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDashboardPort() {
    return dashboardPort;
  }


  public void setDashboardPort(Integer dashboardPort) {
    this.dashboardPort = dashboardPort;
  }


  public V1alpha1DaskClusterSpec envVars(List<V1alpha1DaskClusterSpecEnvVars> envVars) {
    
    this.envVars = envVars;
    return this;
  }

  public V1alpha1DaskClusterSpec addEnvVarsItem(V1alpha1DaskClusterSpecEnvVars envVarsItem) {
    if (this.envVars == null) {
      this.envVars = new ArrayList<>();
    }
    this.envVars.add(envVarsItem);
    return this;
  }

   /**
   * Get envVars
   * @return envVars
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1DaskClusterSpecEnvVars> getEnvVars() {
    return envVars;
  }


  public void setEnvVars(List<V1alpha1DaskClusterSpecEnvVars> envVars) {
    this.envVars = envVars;
  }


  public V1alpha1DaskClusterSpec globalLabels(Map<String, String> globalLabels) {
    
    this.globalLabels = globalLabels;
    return this;
  }

  public V1alpha1DaskClusterSpec putGlobalLabelsItem(String key, String globalLabelsItem) {
    if (this.globalLabels == null) {
      this.globalLabels = new HashMap<>();
    }
    this.globalLabels.put(key, globalLabelsItem);
    return this;
  }

   /**
   * Get globalLabels
   * @return globalLabels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getGlobalLabels() {
    return globalLabels;
  }


  public void setGlobalLabels(Map<String, String> globalLabels) {
    this.globalLabels = globalLabels;
  }


  public V1alpha1DaskClusterSpec image(V1alpha1DaskClusterSpecImage image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecImage getImage() {
    return image;
  }


  public void setImage(V1alpha1DaskClusterSpecImage image) {
    this.image = image;
  }


  public V1alpha1DaskClusterSpec imagePullSecrets(List<V1alpha1DaskClusterSpecImagePullSecrets> imagePullSecrets) {
    
    this.imagePullSecrets = imagePullSecrets;
    return this;
  }

  public V1alpha1DaskClusterSpec addImagePullSecretsItem(V1alpha1DaskClusterSpecImagePullSecrets imagePullSecretsItem) {
    if (this.imagePullSecrets == null) {
      this.imagePullSecrets = new ArrayList<>();
    }
    this.imagePullSecrets.add(imagePullSecretsItem);
    return this;
  }

   /**
   * Get imagePullSecrets
   * @return imagePullSecrets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1DaskClusterSpecImagePullSecrets> getImagePullSecrets() {
    return imagePullSecrets;
  }


  public void setImagePullSecrets(List<V1alpha1DaskClusterSpecImagePullSecrets> imagePullSecrets) {
    this.imagePullSecrets = imagePullSecrets;
  }


  public V1alpha1DaskClusterSpec istioMutualTLSMode(String istioMutualTLSMode) {
    
    this.istioMutualTLSMode = istioMutualTLSMode;
    return this;
  }

   /**
   * Get istioMutualTLSMode
   * @return istioMutualTLSMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIstioMutualTLSMode() {
    return istioMutualTLSMode;
  }


  public void setIstioMutualTLSMode(String istioMutualTLSMode) {
    this.istioMutualTLSMode = istioMutualTLSMode;
  }


  public V1alpha1DaskClusterSpec kerberosKeytab(V1alpha1DaskClusterSpecKerberosKeytab kerberosKeytab) {
    
    this.kerberosKeytab = kerberosKeytab;
    return this;
  }

   /**
   * Get kerberosKeytab
   * @return kerberosKeytab
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecKerberosKeytab getKerberosKeytab() {
    return kerberosKeytab;
  }


  public void setKerberosKeytab(V1alpha1DaskClusterSpecKerberosKeytab kerberosKeytab) {
    this.kerberosKeytab = kerberosKeytab;
  }


  public V1alpha1DaskClusterSpec nannyPort(Integer nannyPort) {
    
    this.nannyPort = nannyPort;
    return this;
  }

   /**
   * Get nannyPort
   * @return nannyPort
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNannyPort() {
    return nannyPort;
  }


  public void setNannyPort(Integer nannyPort) {
    this.nannyPort = nannyPort;
  }


  public V1alpha1DaskClusterSpec networkPolicy(V1alpha1DaskClusterSpecNetworkPolicy networkPolicy) {
    
    this.networkPolicy = networkPolicy;
    return this;
  }

   /**
   * Get networkPolicy
   * @return networkPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecNetworkPolicy getNetworkPolicy() {
    return networkPolicy;
  }


  public void setNetworkPolicy(V1alpha1DaskClusterSpecNetworkPolicy networkPolicy) {
    this.networkPolicy = networkPolicy;
  }


  public V1alpha1DaskClusterSpec podSecurityContext(V1alpha1DaskClusterSpecPodSecurityContext podSecurityContext) {
    
    this.podSecurityContext = podSecurityContext;
    return this;
  }

   /**
   * Get podSecurityContext
   * @return podSecurityContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecPodSecurityContext getPodSecurityContext() {
    return podSecurityContext;
  }


  public void setPodSecurityContext(V1alpha1DaskClusterSpecPodSecurityContext podSecurityContext) {
    this.podSecurityContext = podSecurityContext;
  }


  public V1alpha1DaskClusterSpec podSecurityPolicy(String podSecurityPolicy) {
    
    this.podSecurityPolicy = podSecurityPolicy;
    return this;
  }

   /**
   * Get podSecurityPolicy
   * @return podSecurityPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPodSecurityPolicy() {
    return podSecurityPolicy;
  }


  public void setPodSecurityPolicy(String podSecurityPolicy) {
    this.podSecurityPolicy = podSecurityPolicy;
  }


  public V1alpha1DaskClusterSpec scheduler(V1alpha1DaskClusterSpecScheduler scheduler) {
    
    this.scheduler = scheduler;
    return this;
  }

   /**
   * Get scheduler
   * @return scheduler
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecScheduler getScheduler() {
    return scheduler;
  }


  public void setScheduler(V1alpha1DaskClusterSpecScheduler scheduler) {
    this.scheduler = scheduler;
  }


  public V1alpha1DaskClusterSpec schedulerPort(Integer schedulerPort) {
    
    this.schedulerPort = schedulerPort;
    return this;
  }

   /**
   * Get schedulerPort
   * @return schedulerPort
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSchedulerPort() {
    return schedulerPort;
  }


  public void setSchedulerPort(Integer schedulerPort) {
    this.schedulerPort = schedulerPort;
  }


  public V1alpha1DaskClusterSpec serviceAccount(V1alpha1DaskClusterSpecServiceAccount serviceAccount) {
    
    this.serviceAccount = serviceAccount;
    return this;
  }

   /**
   * Get serviceAccount
   * @return serviceAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecServiceAccount getServiceAccount() {
    return serviceAccount;
  }


  public void setServiceAccount(V1alpha1DaskClusterSpecServiceAccount serviceAccount) {
    this.serviceAccount = serviceAccount;
  }


  public V1alpha1DaskClusterSpec worker(V1alpha1DaskClusterSpecWorker worker) {
    
    this.worker = worker;
    return this;
  }

   /**
   * Get worker
   * @return worker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1DaskClusterSpecWorker getWorker() {
    return worker;
  }


  public void setWorker(V1alpha1DaskClusterSpecWorker worker) {
    this.worker = worker;
  }


  public V1alpha1DaskClusterSpec workerPort(Integer workerPort) {
    
    this.workerPort = workerPort;
    return this;
  }

   /**
   * Get workerPort
   * @return workerPort
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWorkerPort() {
    return workerPort;
  }


  public void setWorkerPort(Integer workerPort) {
    this.workerPort = workerPort;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1DaskClusterSpec v1alpha1DaskClusterSpec = (V1alpha1DaskClusterSpec) o;
    return Objects.equals(this.autoscaling, v1alpha1DaskClusterSpec.autoscaling) &&
        Objects.equals(this.dashboardPort, v1alpha1DaskClusterSpec.dashboardPort) &&
        Objects.equals(this.envVars, v1alpha1DaskClusterSpec.envVars) &&
        Objects.equals(this.globalLabels, v1alpha1DaskClusterSpec.globalLabels) &&
        Objects.equals(this.image, v1alpha1DaskClusterSpec.image) &&
        Objects.equals(this.imagePullSecrets, v1alpha1DaskClusterSpec.imagePullSecrets) &&
        Objects.equals(this.istioMutualTLSMode, v1alpha1DaskClusterSpec.istioMutualTLSMode) &&
        Objects.equals(this.kerberosKeytab, v1alpha1DaskClusterSpec.kerberosKeytab) &&
        Objects.equals(this.nannyPort, v1alpha1DaskClusterSpec.nannyPort) &&
        Objects.equals(this.networkPolicy, v1alpha1DaskClusterSpec.networkPolicy) &&
        Objects.equals(this.podSecurityContext, v1alpha1DaskClusterSpec.podSecurityContext) &&
        Objects.equals(this.podSecurityPolicy, v1alpha1DaskClusterSpec.podSecurityPolicy) &&
        Objects.equals(this.scheduler, v1alpha1DaskClusterSpec.scheduler) &&
        Objects.equals(this.schedulerPort, v1alpha1DaskClusterSpec.schedulerPort) &&
        Objects.equals(this.serviceAccount, v1alpha1DaskClusterSpec.serviceAccount) &&
        Objects.equals(this.worker, v1alpha1DaskClusterSpec.worker) &&
        Objects.equals(this.workerPort, v1alpha1DaskClusterSpec.workerPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoscaling, dashboardPort, envVars, globalLabels, image, imagePullSecrets, istioMutualTLSMode, kerberosKeytab, nannyPort, networkPolicy, podSecurityContext, podSecurityPolicy, scheduler, schedulerPort, serviceAccount, worker, workerPort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1DaskClusterSpec {\n");
    sb.append("    autoscaling: ").append(toIndentedString(autoscaling)).append("\n");
    sb.append("    dashboardPort: ").append(toIndentedString(dashboardPort)).append("\n");
    sb.append("    envVars: ").append(toIndentedString(envVars)).append("\n");
    sb.append("    globalLabels: ").append(toIndentedString(globalLabels)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imagePullSecrets: ").append(toIndentedString(imagePullSecrets)).append("\n");
    sb.append("    istioMutualTLSMode: ").append(toIndentedString(istioMutualTLSMode)).append("\n");
    sb.append("    kerberosKeytab: ").append(toIndentedString(kerberosKeytab)).append("\n");
    sb.append("    nannyPort: ").append(toIndentedString(nannyPort)).append("\n");
    sb.append("    networkPolicy: ").append(toIndentedString(networkPolicy)).append("\n");
    sb.append("    podSecurityContext: ").append(toIndentedString(podSecurityContext)).append("\n");
    sb.append("    podSecurityPolicy: ").append(toIndentedString(podSecurityPolicy)).append("\n");
    sb.append("    scheduler: ").append(toIndentedString(scheduler)).append("\n");
    sb.append("    schedulerPort: ").append(toIndentedString(schedulerPort)).append("\n");
    sb.append("    serviceAccount: ").append(toIndentedString(serviceAccount)).append("\n");
    sb.append("    worker: ").append(toIndentedString(worker)).append("\n");
    sb.append("    workerPort: ").append(toIndentedString(workerPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

