apiVersion: distributed-compute.dominodatalab.com/v1alpha1
kind: DaskCluster
metadata:
  name: example
spec:
  image:
    registry: ""
    repository: daskdev/dask
    tag: 2021.4.1
    pullPolicy: IfNotPresent

  schedulerPort: 8786
  dashboardPort: 8787
  workerPort: 3000
  nannyPort: 4000

  worker:
    replicas: 1

  # common fields below

  serviceAccount:
    name: ""
