apiVersion: distributed-compute.dominodatalab.com/v1alpha1
kind: MPIJob
metadata:
  name: example
spec:
  # image:
  #   registry: ""
  #   repository: horovod/horovod
  #   tag: 0.22.1
  #   pullPolicy: IfNotPresent

  # networkPolicy:
  #   enabled: true
  #   clientLabels: {}
  #   dashboardLabels: {}

  # serviceAccount:
  #   name: ""
  #   automountServiceAccountToken: false

  # podSecurityContext:
  #   runAsUser:
  #   runAsGroup:
  #   fsGroup:

  # kerberosKeytab:
  #   contents:
  #   mountPath:

  # globalLabels: {}
  # envVars: []
  # imagePullSecrets: []
  # podSecurityPolicy: ""
  # istioMutualTLSMode: ""

  launcher:
    command:
      - mpirun
      - --allow-run-as-root
      - python
      - tensorflow2/tensorflow2_synthetic_benchmark.py
      - --no-cuda
      - --batch-size=1
      - --num-warmup-batches=1
      - --num-iters=2
      - --num-batches-per-iter=1
    # labels: {}
    # annotations: {}
    # nodeSelector: {}
    # affinity: {}
    # tolerations: []
    # initContainers: []
    # volumes: []
    # volumeMounts: []
    # volumeClaimTemplates: []
    # resources: {}

  worker:
    # slots: 1
    # replicas: 2
    # labels: {}
    # annotations: {}
    # nodeSelector: {}
    # affinity: {}
    # tolerations: []
    # initContainers: []
    # volumes: []
    # volumeMounts: []
    # volumeClaimTemplates: []
    # resources: {}
