apiVersion: distributed-compute.dominodatalab.com/v1alpha1
kind: MPICluster
metadata:
  name: example
spec:
  # image:
  #   registry: ""
  #   repository: horovod/horovod
  #   tag: 0.22.1
  #   pullPolicy: IfNotPresent

  # networkPolicy:
  #   enabled: true
  #   clientLabels: {}
  #   dashboardLabels: {}

  # serviceAccount:
  #   name: ""
  #   automountServiceAccountToken: false

  # podSecurityContext:
  #   runAsUser:
  #   runAsGroup:
  #   fsGroup:

  # kerberosKeytab:
  #   contents:
  #   mountPath:

  # globalLabels: {}
  # envVars: []
  # imagePullSecrets: []
  # podSecurityPolicy: ""
  # istioMutualTLSMode: ""

  # additionalClientPorts:
  #   - name: http-api-proxy
  #     port: 8899
  #     targetPort: 8899
  #     protocol: TCP

  worker:
    # replicas: 1
    sharedSSHSecret: ""
    # userName:
    # userID:
    # groupName:
    # groupID:
    # homeDir: /mnt
    # labels: {}
    # annotations: {}
    # nodeSelector: {}
    # affinity: {}
    # tolerations: []
    # initContainers: []
    # volumes: []
    # volumeMounts: []
    # volumeClaimTemplates: []
    # resources: {}
