apiVersion: v1
kind: ServiceAccount
metadata:
  name: dask-notebook

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dask-notebook
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - privileged

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dask-notebook
roleRef:
  kind: Role
  name: dask-notebook
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: dask-notebook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-notebook
  labels:
    app: dask-notebook
    dask-client: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-notebook
  template:
    metadata:
      labels:
        app: dask-notebook
        dask-client: "true"
    spec:
      serviceAccountName: dask-notebook
      containers:
      - name: dask-notebook
        image: daskdev/dask-notebook:2021.7.2
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: dask-notebook
spec:
  type: NodePort
  selector:
    app: dask-notebook
  ports:
  - protocol: TCP
    name: tcp-ui
    port: 8888
    targetPort: 8888
