apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-ray

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-ray
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs:     ["use"]
    resourceNames:
      - privileged

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-ray
roleRef:
  kind: Role
  name: test-ray
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: test-ray

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ray
  labels:
    app: test-ray
    version: 1.6.0-cpu
    ray-client: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ray
  template:
    metadata:
      labels:
        app: test-ray
        version: 1.6.0-cpu
        ray-client: "true"
    spec:
      serviceAccountName: test-ray
      containers:
      - name: ray
        image: rayproject/ray:1.6.0-cpu
        command: ["sleep", "86400"]
