/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dominodatalab.distributedcomputeoperator.ray.models;

import java.util.Objects;
import java.util.Arrays;
import com.dominodatalab.distributedcomputeoperator.ray.models.V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-04T16:37:47.111Z[Etc/UTC]")
public class V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference {
  public static final String SERIALIZED_NAME_MATCH_EXPRESSIONS = "matchExpressions";
  @SerializedName(SERIALIZED_NAME_MATCH_EXPRESSIONS)
  private List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> matchExpressions = null;

  public static final String SERIALIZED_NAME_MATCH_FIELDS = "matchFields";
  @SerializedName(SERIALIZED_NAME_MATCH_FIELDS)
  private List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> matchFields = null;


  public V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference matchExpressions(List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> matchExpressions) {
    
    this.matchExpressions = matchExpressions;
    return this;
  }

  public V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference addMatchExpressionsItem(V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions matchExpressionsItem) {
    if (this.matchExpressions == null) {
      this.matchExpressions = new ArrayList<>();
    }
    this.matchExpressions.add(matchExpressionsItem);
    return this;
  }

   /**
   * Get matchExpressions
   * @return matchExpressions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> getMatchExpressions() {
    return matchExpressions;
  }


  public void setMatchExpressions(List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> matchExpressions) {
    this.matchExpressions = matchExpressions;
  }


  public V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference matchFields(List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> matchFields) {
    
    this.matchFields = matchFields;
    return this;
  }

  public V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference addMatchFieldsItem(V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions matchFieldsItem) {
    if (this.matchFields == null) {
      this.matchFields = new ArrayList<>();
    }
    this.matchFields.add(matchFieldsItem);
    return this;
  }

   /**
   * Get matchFields
   * @return matchFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> getMatchFields() {
    return matchFields;
  }


  public void setMatchFields(List<V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreferenceMatchExpressions> matchFields) {
    this.matchFields = matchFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference v1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference = (V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference) o;
    return Objects.equals(this.matchExpressions, v1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference.matchExpressions) &&
        Objects.equals(this.matchFields, v1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference.matchFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchExpressions, matchFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RayClusterSpecHeadAffinityNodeAffinityPreference {\n");
    sb.append("    matchExpressions: ").append(toIndentedString(matchExpressions)).append("\n");
    sb.append("    matchFields: ").append(toIndentedString(matchFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

