apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dco.rbac.managerName" . }}.{{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
rules:
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - daskclusters
  - rayclusters
  - sparkclusters
  - mpiclusters
  verbs:
  - patch
  - update
  - list
  - watch
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - daskclusters/status
  - rayclusters/status
  - sparkclusters/status
  - mpiclusters/status
  verbs:
  - update
- apiGroups:
  - distributed-compute.dominodatalab.com
  resources:
  - daskclusters/finalizers
  - rayclusters/finalizers
  - sparkclusters/finalizers
  - mpiclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - update
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - delete
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - update
  - list
  - watch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - domino-restricted
  verbs:
  - use
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - security.istio.io
  resources:
  - peerauthentications
  verbs:
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - create
  - update
  - list
  - watch
{{- if .Values.config.enableLeaderElection }}
- apiGroups:
    - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
{{- end }}
