apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- if .Values.prometheus.enabled }}
        prometheus.io/port: "{{ .Values.config.metricsPort }}"
        prometheus.io/scrape: "true"
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | trimSuffix "\n" | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dco.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "dco.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - start
            {{- with .Values.config }}
            - --webhook-server-port={{ .webhookPort }}
            - --metrics-bind-address=:{{ .metricsPort }}
            - --health-probe-bind-address=:{{ .healthProbePort }}
            {{- with .watchNamespaces }}
            - --namespaces={{ . | join "," }}
            {{- end }}
            {{- if .enableLeaderElection }}
            - --leader-elect
            {{- end }}
            {{- if .logDevelopmentMode }}
            - --zap-devel
            {{- end }}
            {{- with .logEncoder }}
            - --zap-encoder={{ . }}
            {{- end }}
            {{- with .logLevel }}
            - --zap-log-level={{ . }}
            {{- end }}
            {{- with .logStacktraceLevel }}
            - --zap-stacktrace-level={{ . }}
            {{- end }}
            {{- end }}
            {{- if .Values.istio.enabled }}
            - --istio-enabled
            {{- end }}
            {{- with .Values.mpi.initImage }}
            - --mpi-init-image={{- include "common.images.image" (dict "imageRoot" . $) -}}
            {{- end }}
            {{- with .Values.mpi.syncImage }}
            - --mpi-sync-image={{- include "common.images.image" (dict "imageRoot" . $) -}}
            {{- end }}
          {{- with .Values.podEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: webhooks
              containerPort: {{ .Values.config.webhookPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.config.metricsPort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.config.healthProbePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          volumeMounts:
            - name: webhook-cert
              readOnly: true
              mountPath: /tmp/k8s-webhook-server/serving-certs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: webhook-cert
          secret:
            secretName: {{ include "dco.webhook.secret" . }}
            defaultMode: 420
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
