{{- if and (.Values.istio.enabled) (.Values.istio.httpIdleTimeout.timeout)  }}
{{- $justRootConfigNamespace := list .Values.istio.rootConfigNamespace }}
{{- $defaultNamespaces := .Values.config.watchNamespaces | default $justRootConfigNamespace }}
{{- $namespaces := .Values.istio.httpIdleTimeout.namespaces | default $defaultNamespaces }}
{{- range $namespace := $namespaces }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: distributed-compute-cluster-envoyfilter
  namespace: {{ $namespace }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/managed-by: distributed-compute-operator
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: "envoy.filters.network.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          common_http_protocol_options:
            idle_timeout: {{ $.Values.istio.httpIdleTimeout.timeout }}
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
          idle_timeout: {{ $.Values.istio.httpIdleTimeout.timeout }}
---
{{- end }}
{{- end }}
