{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: {{ .Values.config.webhookPort }}
      protocol: TCP
    - port: {{ .Values.config.healthProbePort }}
      protocol: TCP
    - port: {{ .Values.config.metricsPort }}
      protocol: TCP
{{- end }}
