apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "common.names.fullname" . }}.{{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- include "dco.webhook.annotation" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "dco.webhook.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-distributed-compute-dominodatalab-com-v1alpha1-mpijob
    failurePolicy: Fail
    name: mmpijob.kb.io
    rules:
      - apiGroups:
          - distributed-compute.dominodatalab.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - mpijobs
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "dco.webhook.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-distributed-compute-dominodatalab-com-v1alpha1-daskcluster
    failurePolicy: Fail
    name: mdaskcluster.kb.io
    rules:
      - apiGroups:
          - distributed-compute.dominodatalab.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - daskclusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "dco.webhook.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-distributed-compute-dominodatalab-com-v1alpha1-raycluster
    failurePolicy: Fail
    name: mraycluster.kb.io
    rules:
      - apiGroups:
          - distributed-compute.dominodatalab.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rayclusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "dco.webhook.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-distributed-compute-dominodatalab-com-v1alpha1-sparkcluster
    failurePolicy: Fail
    name: msparkcluster.kb.io
    rules:
      - apiGroups:
          - distributed-compute.dominodatalab.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - sparkclusters
    sideEffects: None
