apiVersion: v1
kind: Service
metadata:
  name: {{ include "dco.webhook.service" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhooks
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
