apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "dco.fullname" . }}
  labels:
    {{- include "dco.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "dco.webhook.certificate" . }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "dco.webhook.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-distributed-compute-dominodatalab-com-v1alpha1-raycluster
    failurePolicy: Fail
    name: mraycluster.kb.io
    rules:
      - apiGroups:
          - distributed-compute.dominodatalab.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rayclusters
    sideEffects: None
