apiVersion: v1
kind: Service
metadata:
  name: {{ include "dco.webhook.service" . }}
  labels:
    {{- include "dco.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    {{- include "dco.selectorLabels" . | nindent 4 }}
